services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: reservas
      POSTGRES_USER: reservas
      POSTGRES_PASSWORD: reservas
    ports: ["5433:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]
  api:
    build: .
    env_file: .env
    environment:
      - DB_URL=jdbc:postgresql://postgres:5432/reservas
      - DB_USERNAME=reservas
      - DB_PASSWORD=changeme
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - APP_JWT_SECRET
      - SPRING_PROFILES_ACTIVE=prod
    depends_on: [postgres, redis]
    ports: ["8080:8080"]

volumes:
  pgdata:
