server:
  port: ${PORT:8080}
  forward-headers-strategy: framework

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/reservas}
    username: ${DB_USERNAME:reservas}
    password: ${DB_PASSWORD:reservas}
  mail:
    host: ${MAIL_HOST:localhost}
    port: ${MAIL_PORT:2525}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  cache:
    type: simple

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    org.springframework: INFO