ALTER TABLE business
  ADD COLUMN IF NOT EXISTS cuisine VARCHAR(255);
ALTER TABLE business
  ADD COLUMN IF NOT EXISTS address VARCHAR(255);
ALTER TABLE business
  ADD COLUMN IF NOT EXISTS phone VARCHAR(255);
ALTER TABLE business
  ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE business
  ADD COLUMN IF NOT EXISTS table_layout_json TEXT;
